### ISSUE TITLE
[Bug]: M1 Pro版本MacBook Pro无法开启系统代理

### ISSUE THREAD

**Issue by Martinfeng** [Fndroid/clash_for_windows_pkg#2379]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.6-arm64

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

Monterey 12.0.1

### 问题描述

点击system proxy没有反应，不会跳出输入密码的窗口。但是不一定在每个M1 Pro的Mac上复现，猜测还是适配的问题吧。

### 复现步骤

setting-general-system proxy，点击后没有反应，按钮也不会右滑。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by WAIGITNG** [comment]
不清楚是系统问题还是软件问题，每次都要重启电脑才能正常连接，使用途中退出再打开不能连接外网，暂时断开外网再打开都可以，唯独是退出软件后，必须要重启电脑才能连接外网；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fndroid/clash_for_windows_pkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 下午2:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Fndroid/clash_for_windows_pkg] [Bug]:  (Issue #2379)





 
请认真检查以下清单中的每一项
  
 已经搜索过，没有发现类似issue
 
 已经搜索过文档，没有发现相关内容
 
 已经尝试使用过最新版，问题依旧存在
 
 使用的是官方版本（未替换及修改过安装目录程序文件）
  
软件版本
 
0.18.6
 
操作系统
 
macOS arm64(M1,M1*)
 
系统版本
 
Monterey 12.0.1
 
问题描述
 
点击system proxy没有反应，不会跳出输入密码的窗口。但是不一定在每个M1 Pro的Mac上复现，猜测还是适配的问题吧。
 
复现步骤
 
setting-general-system proxy，点击后没有反应，按钮也不会右滑。
 
日志文件
 logs
 
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行  

 
其他补充
 
No response
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Fndroid** [comment]
授权窗口没弹出来的话先按这个手动安装一下service mode吧 https://github.com/Fndroid/clash_for_windows_pkg/issues/2159#issuecomment-903138367

因为这个实现是第三方的框架，要有真机调试下才能知道原因暂时解决不了

**Comment by Martinfeng** [comment]
更新到了0.18.7，已经完美解决可以在M1 Pro上使用了。

**Comment by Fndroid** [comment]
我实际上也没改。。能用就暂时关闭吧

**Comment by CharlesLiuyx** [comment]
出现最新版本 Monterey 系统内，无法开启 Service Mode
已经尝试手动开启 Service Mode，但遇到了下面的问题无法解决。
```
Load failed: 122: Path had bad ownership/permissions
```

最新版本的 M1 Max 电脑，Mac OS 12.0.0 Monterey

**Comment by Fndroid** [comment]
@CharlesLiuyx https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85-macos 用这个脚本试试？

**Comment by CharlesLiuyx** [comment]
感谢回复，因为昨天没有解决，换用了 ClashX。

记录一下环境信息：
Mac OS Version：12.0.0 Monterey
机器型号：M1 Max 2021 16寸

ClashX 安装的时候会自动弹出几个授权弹框。点击后 ClashX 就能正常链接了。

> @CharlesLiuyx https://docs.cfw.lbyczf.com/contents/questions.html#service-mode-%E6%97%A0%E6%B3%95%E5%AE%89%E8%A3%85-macos 用这个脚本试试？
