### ISSUE TITLE
[Bug]: macOS 系统安装cfw后，启动cfw提示文件已损坏

### ISSUE THREAD

**Issue by djunhao** [Fndroid/clash_for_windows_pkg#3738]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.8, 0.20.9

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

macOS ventura 13.0.1

### 问题描述

无论是从brew安装，还是从github下载安装，启动cfw的时候，系统均提示文件已损坏。

### 复现步骤

下载安装后，启动cfw即可复现。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by djunhao** [comment]
已找到解决方案。

**Comment by chouxiang99** [comment]
> 已找到解决方案。

后来怎么解决的呀    我也遇到了同样的问题   感谢

**Comment by Saigut** [comment]
问下你是怎么解决的？

**Comment by chouxiang99** [comment]
有一串代码可以解决   这两天在外面旅游  回去给你发发自我的 iPhone在 2023年4月29日，15:21，Saigut ***@***.***> 写道：﻿
问下你是怎么解决的？

**Comment by Saigut** [comment]
> 有一串代码可以解决   这两天在外面旅游  回去给你发发自我的 iPhone在 2023年4月29日，15:21，Saigut ***@***.***> 写道：﻿ 问下你是怎么解决的？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

我找到解决问题的那行命令了，谢谢

**Comment by chouxiang99** [comment]
好的好的    而且我发现这个代码  如果其他软件有类似的报错  改一下最后的应用地址  都能用发自我的 iPhone在 2023年4月30日，13:08，Saigut ***@***.***> 写道：﻿

有一串代码可以解决   这两天在外面旅游  回去给你发发自我的 iPhone在 2023年4月29日，15:21，Saigut @.> 写道：﻿ 问下你是怎么解决的？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

我找到解决问题的那行命令了，谢谢
