### ISSUE TITLE
[Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题

### ISSUE THREAD

**Issue by xk-mt** [Fndroid/clash_for_windows_pkg#4626]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20、、0.15.0

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 22H2

### 问题描述

我两台笔记本电脑，安装了一个最新版（0.20.20）和两个老版本（0.19.15、0.15.0），均出现问题

问题：启动clash后任务栏无图标显示，但有占位，是透明的，无法单击，无法右击
尝试解决：
1.在任务栏右键选择”任务栏设置“，点击”选择哪些图标显示在任务栏上“勾选”通知区域始终显示所有图标“（未解决）
2.在”clash“的”Settings“里面”Appearance“其中”Default Icon Path“和”System Proxy On lcon Path“都选择了ico文件（未解决）
3.尝试安装老版本，0.20.20、0.19.15、0.15.0这三个版本均未显示（未解决）
4.重启电脑，卸载软件（未解决）

### 复现步骤

未知，我两台笔记本都出现该问题，系统都是：Windows 10 专业版 22H2。均安装360和火绒，从下载安装到启动均未开启任何杀毒软件，

### 日志文件

未找打日志文件，未搜索到clash log

### 其他补充

所有配置均为默认。

**Comment by xk-mt** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/0fb538db-dc76-4e26-82d0-3568033dc452)

**Comment by xk-mt** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/02cd1ecb-73d3-4fe6-8166-89008a32ec5a)

**Comment by EmptyIrony** [comment]
检查Settings下的Hide Tray Icon是否关闭

**Comment by xk-mt** [comment]
> 检查Settings下的Hide Tray Icon是否关闭

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/77874955/18b5284f-7581-4de5-b7e9-7c2e75e03ebb)

**Comment by xk-mt** [comment]
顶

**Comment by Halfknow** [comment]
遇到了同样的问题，哥们有解决这个问题嘛

**Comment by xk-mt** [comment]
> 遇到了同样的问题，哥们有解决这个问题嘛

没有，不过咱俩可以对比一下都干了什么，比如下载了什么软件，操作了什么设置

**Comment by Halfknow** [comment]
> > 遇到了同样的问题，哥们有解决这个问题嘛
> 
> 没有，不过咱俩可以对比一下都干了什么，比如下载了什么软件，操作了什么设置

我下载了火绒、everything、powertoy、谷歌云盘，但我台式也装了这些软件，比笔记本更全更多就没问题，就笔记本win11的22H2出现了这个问题

**Comment by xk-mt** [comment]
火绒、everything

**Comment by xk-mt** [comment]
我怀疑是火绒

**Comment by xk-mt** [comment]
everything只是搜索，应该是火绒，但是怎么恢复呢

**Comment by Halfknow** [comment]
你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题

**Comment by xk-mt** [comment]
没有改过，但是我用了火绒以后，火绒基本功能用完没多久就这样了，要不你试试把全部功能用一遍看看

**Comment by xk-mt** [comment]
> 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题

  怎么样，有新进展吗

**Comment by tlsban** [comment]
> > 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题
> 
> 怎么样，有新进展吗

我也遇到了这个问题，解决方法是使用管理员权限启动clash

**Comment by xk-mt** [comment]
> > > 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题
> > 
> > 
> > 怎么样，有新进展吗
> 
> 我也遇到了这个问题，解决方法是使用管理员权限启动clash

还是不行，我尝试了源文件管理员启动，还是不行

**Comment by qsyzzz** [comment]
我也碰到这个问题了，更新到最新的版本0.20.37就不行了

**Comment by Halfknow** [comment]
> > > 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题
> > 
> > 
> > 怎么样，有新进展吗
> 
> 我也遇到了这个问题，解决方法是使用管理员权限启动clash

我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题

**Comment by xk-mt** [comment]
> > > > 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题
> > > 
> > > 
> > > 怎么样，有新进展吗
> > 
> > 
> > 我也遇到了这个问题，解决方法是使用管理员权限启动clash
> 
> 我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题

你改过注册表吗，或者使用过火绒，或者360等

**Comment by xk-mt** [comment]
> 之前卸载过旧版，然后从GitHub上卸载最新版安装之后就发现不出现图标的问题了，管理员权限打开也么用。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月30日(星期一) 上午9:33 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题 怎么样，有新进展吗 我也遇到了这个问题，解决方法是使用管理员权限启动clash 我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题 你改过注册表吗，或者使用过火绒，或者360等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，等待解决，你用过360或者火绒吗

**Comment by qsyzzz** [comment]
有用火绒



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 米汤 ***@***.***&gt;
发送时间: 2023年11月2日 09:58
收件人: Fndroid/clash_for_windows_pkg ***@***.***&gt;
抄送: qsyzzz ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626)





  
之前卸载过旧版，然后从GitHub上卸载最新版安装之后就发现不出现图标的问题了，管理员权限打开也么用。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年10月30日(星期一) 上午9:33 收件人: @.&gt;; 抄送: @.@.&gt;; @.&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题 怎么样，有新进展吗 我也遇到了这个问题，解决方法是使用管理员权限启动clash 我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题 你改过注册表吗，或者使用过火绒，或者360等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
是的，等待解决，你用过360或者火绒吗

**Comment by xk-mt** [comment]
> 有用火绒 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 米汤 ***@***.***&gt; 发送时间: 2023年11月2日 09:58 收件人: Fndroid/clash_for_windows_pkg ***@***.***&gt; 抄送: qsyzzz ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 之前卸载过旧版，然后从GitHub上卸载最新版安装之后就发现不出现图标的问题了，管理员权限打开也么用。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年10月30日(星期一) 上午9:33 收件人: @.&gt;; 抄送: @.@.&gt;; @.&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题 怎么样，有新进展吗 我也遇到了这个问题，解决方法是使用管理员权限启动clash 我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题 你改过注册表吗，或者使用过火绒，或者360等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 是的，等待解决，你用过360或者火绒吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

目前看来大家都用了火绒才这样

**Comment by qsyzzz** [comment]
坐等下一波更新🤣好多人出现这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 米汤 ***@***.***&gt;
发送时间: 2023年11月2日 10:01
收件人: Fndroid/clash_for_windows_pkg ***@***.***&gt;
抄送: qsyzzz ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626)





  
有用火绒 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: 米汤 @.&gt; 发送时间: 2023年11月2日 09:58 收件人: Fndroid/clash_for_windows_pkg @.&gt; 抄送: qsyzzz @.&gt;, Comment @.&gt; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 之前卸载过旧版，然后从GitHub上卸载最新版安装之后就发现不出现图标的问题了，管理员权限打开也么用。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年10月30日(星期一) 上午9:33 收件人: @.&gt;; 抄送: @.@.&gt;; @.&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题 怎么样，有新进展吗 我也遇到了这个问题，解决方法是使用管理员权限启动clash 我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题 你改过注册表吗，或者使用过火绒，或者360等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 是的，等待解决，你用过360或者火绒吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
目前看来大家都用了火绒才这样

**Comment by xk-mt** [comment]
> 坐等下一波更新🤣好多人出现这个问题 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 米汤 ***@***.***&gt; 发送时间: 2023年11月2日 10:01 收件人: Fndroid/clash_for_windows_pkg ***@***.***&gt; 抄送: qsyzzz ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 有用火绒 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: 米汤 @.&gt; 发送时间: 2023年11月2日 09:58 收件人: Fndroid/clash_for_windows_pkg @.&gt; 抄送: qsyzzz @.&gt;, Comment @.&gt; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 之前卸载过旧版，然后从GitHub上卸载最新版安装之后就发现不出现图标的问题了，管理员权限打开也么用。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年10月30日(星期一) 上午9:33 收件人: @.&gt;; 抄送: @.@.&gt;; @.&gt;; 主题: Re: [Fndroid/clash_for_windows_pkg] [Bug]: windows右下角状态托盘不显示clash图标，（十万火急❤）两台设备都出现一样的问题 (Issue #4626) 你之前有动过注册表吗，我出现这个问题之前删过一部分注册表，不知道是不是这个原因，我另一台有火绒的也没问题，系统环境和笔记本的几乎一模一样，没有出现这个问题 怎么样，有新进展吗 我也遇到了这个问题，解决方法是使用管理员权限启动clash 我用管理员权限启动clash也没用，同样是22h2，目前升级至23h2还是存在问题 你改过注册表吗，或者使用过火绒，或者360等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 是的，等待解决，你用过360或者火绒吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 目前看来大家都用了火绒才这样 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我等了好久，一直没有任何回复
